### ISSUE TITLE
kgram_freqs cannot be saved via saveRDS()

### ISSUE THREAD

**Issue by blackline-lye** [vgherard/kgrams#21]
Hi there, 

I noticed kgram_freqs objects (and also language models I suspect) cannot be saved with R saveRDS(). Once kgram_freqs is loaded back with readRDS() it appears to have invalid C pointers, leading to errors when trying to use the object.

Is there a way to store a kgram_freqs on the disk for later reload?

Thanks!

**Comment by vgherard** [comment]
Hi @blackline-lye , sorry for the ultra-late response. 

Correct, these objects cannot be saved with `saveRDS()`, because the R object being serialized by this function is indeed a pointer to a C++ object, which only exists in memory during the length of the R session. 

Adding the possibility to serialize the underlying C++ objects has been on my feature wishlist for a long time, I hope I will eventually be able to implement it, but definitely this won't happen in the immediate.

Thanks for the input!

**Comment by andreanini** [comment]
Dear Valerio,

I was wondering if this feature is ever coming to the package? I am extremely grateful for this package and for all the documentation you made. Being able to save the objects would just make it perfect. I had a look around to see if I could figure out a way myself but I'm too ignorant of C++ to do that!

Thanks anyway for releasing it and for all your work on the documentation.

**Comment by vgherard** [comment]
Ciao @andreanini, thanks for your kind words and for the input, I appreciate it a lot :) 

Regarding being able to save objects to file: I'm sorry, but I am not planning to add this feature. Even though I understand the problem you guys raise, doing this would require an effort that I don't see fully justified by the functionality added.

To explain a bit the problem: k-gram frequencies and models are stored internally through a somewhat complicated structure of C++ hash tables and pointers. To "save" these objects there would be two ways to go:

- Serialize the C++ objects (as opposed to the R objects as the OP was suggesting)... I fear this would be a nightmare, and would require a set of external dependencies to be added to the package.
- An intermediate solution: output k-gram frequencies to some custom text formats, as Google does with its "Ngram corpora" (see e.g. [here](https://storage.googleapis.com/books/ngrams/books/datasetsv3.html)). I call this an intermediate solution because it would allow compressing the input needed to load a model, but would still require building the data structures from scratch at each load.

All in all, I feel this would be too complex for the purpose of this package, which at the end of the day is to experiment with small language models.

I am curious though about your specific use case, how are you using the package? And what do you think would be the added value of saving models, wrt. training them each time for scratch?

**Comment by andreanini** [comment]
ciao @vgherard! I absolutely understand.
My field is authorship analysis and I'm experimenting with these kinds of simple language models. It turns out that they can be quite useful for these tasks. Your package is extremely fast at building these models so, in reality, I did not have to save them so far but I can see how it might be useful to do so when I carry out more complex research on larger data sets. I predict that in those cases it is going to be faster and more economical to create and store a language model rather than storing the corpus and rebuilding the model at every run. I might one day get to the bottom of this and find a solution and, if and when this happens, I will contact you and share my code.
I might indeed get in touch with the people behind [quanteda](https://github.com/quanteda/quanteda), which also uses C++ for processing large matrices, and which, if I'm not mistaken, can however be saved as R objects.
Thank you again for the package!

**Comment by vgherard** [comment]
@andreanini I see. Yeah, that sounds like a good idea, `{quanteda}` is definitely more maintained than this package, and they will surely be able to support you. And sure, thanks, keep me in the loop! :-)

Closing this issue.

PS: I'm quite curious about this specific application! If you have some published work of yours (or interesting references), would you be so kind to send a link to vgherard840@gmail.com ? Thank you!
