### ISSUE TITLE
How use k-grams model to predict new word ?

### ISSUE THREAD

**Issue by udriss** [vgherard/kgrams#22]
@vgherard, thank you for this very interesting package. 
Is it possible to predict new words by using a model building with `k-grams` package ?
I know it is possible with the package `sbo`.

**Comment by vgherard** [comment]
Hi @udriss, thank you! 

I currently don't have a `predict()` method implemented for `language_model` objects, but it's shouldn't be difficult at all to implement one. 

Basically, `predict(model, input)` should look for all possible completions for the given `input`, so something like (schematically):

```{r}
preds <- tibble(completion = dictionary(model), prob = predict(model, input))
preds %>% arrange(desc(prob)) %>% head(k)
```
should provide the top `k` word completions of the `input`. This has time complexity O(V log V), where V is the size of the dictionary, so that as long as you have a tiny dictionary, it could provide a working solution.

Let me know if this works and/or you need further assistance in doing this properly.

Cheers!
V

**Comment by vgherard** [comment]
Hi @udriss, I've closed this stale issue, please ping me if you need more support.

**Comment by udriss** [comment]
Hi @vgherard !

Thank you very much for all your clear details.
It was a pleasure. If any need, I'll not hesitate.
